### ISSUE TITLE
Feature request: Support for chrome's dark mode

### ISSUE THREAD

**Issue by selbekk** [nitin42/react-perf-devtool#1]
I can't really use this plugin because I prefer the dark mode theme in chrome's dev tools. 

![image](https://user-images.githubusercontent.com/1307267/34079240-01e5b652-e32a-11e7-9533-af1a9af1d194.png)

Can you add support for this mode as well?

**Comment by nitin42** [comment]
Oh it looks ugly in dark mode. I'll try to add support for this !

**Comment by JeffersonFilho** [comment]
I was about to say that! Hahahha

**Comment by nitin42** [comment]
Can you come up with a PR for this ? That'd be great because right now I'm working on adding more features so it would be nice if @selbekk or you can work on PR that would add support for dark mode. There is an API for this - `chrome.devtools.panel.themeName` which returns 'default' or 'dark' mode. 

For styling, I am using the plain old `<style>` tag so you can find the default (current) styles for this extension.

If you need some more help, let me know!

**Comment by selbekk** [comment]
Here's the PR: https://github.com/nitin42/react-perf-devtool/pull/6

**Comment by nitin42** [comment]
AMAZING!! Thank you so much 😃
