### ISSUE TITLE
How to get it running?

### ISSUE THREAD

**Issue by Anenth** [nitin42/react-perf-devtool#15]
I tried to use it but its just showing 

> Pending Events: 0
> An error occurred while collecting the measures. To resolve this error, try these solutions:
> Register a top level observer in your index.js file. See the detailed documentation on how to register a top level listener (an observer) in your React app.
> 
> Refresh the the page or reload the inspected window if you've registered the observer.

I tried adding  `registerObserver`, still same issue.
What is plugin looking for? How does the plugin work?

**Comment by nitin42** [comment]
Strange. Do the following things in order:

1. Install react-perf-devtool
2. const registerObserver = require('react-perf-devtool')
3. registerObserver()
4. Install the extension 
5. Start the local dev server
6. Open the extension 
7. Reload it if necessary 

Let me know!

**Comment by nitin42** [comment]
Also, I've explained in much detailed in docs about the use of registerObserver and how it can be used to display the measures and stats. Try to read the docs once properly and see if things work out. Else, I'm happy to help you!

**Comment by Anenth** [comment]
@nitin42 I will try it again in the evening

**Comment by nitin42** [comment]
Sure. Everything seems to be working fine from my side!

Just read the docs carefully 😅

**Comment by nitin42** [comment]
Is it working now?

**Comment by Anenth** [comment]
Couldn't get it working, I tried it on a fairly complex project. 
also what did you mean by `Start the local dev server`?

**Comment by nitin42** [comment]
Working for me (probably for most of the users also). May be read the docs or check to see if you're following the instructions well enough to make it work!

**Comment by Anenth** [comment]
@nitin42
I don't really understand the instructions, What am I missing? The only thing required in the source file is `registerObserver()` right? 

https://codesandbox.io/s/7222mym8qq

**Comment by nitin42** [comment]
hmm... `registerObserver` accumulates all the measures, parse them and create a concrete data structure containing the information required by the devtool which is shared through the `window` object.

High level picture:

```
Performance measure  ---->  stored on window object as ---->  window.__REACT_PERF_DEVTOOL_GLOBAL_STORE__  ---> this is then evaluated inside the inspected window i.e the devtool
```

**Comment by Anenth** [comment]
and why is it not working here codesandbox.io/s/7222mym8qq ?

**Comment by nitin42** [comment]
Interesting! Well, for the actual use case, you should be using the tool for inspecting the app you're working and not the prototype that you're building using codesandbox. Also, such tools are only useful if you've graduated your program from working stage to a stable and refactored version. Then you can use this tool to profile the components to see what part of your React codebase needs optimisation.

Don't use it parallel to your development cycle else you will be confused and it will create or add additional constraints to your workflow.

Example - You are using the tool in codesandbox while building a simple version of your app. The stats from the tool show that you need to optimise this part. You then need to change the behaviour and logic of your app at the same time. Think about how much complexity it could add.

But, I am definitely going to do some research on why it is not working with online IDEs. Thanks for your suggestion though. I am re-opening this issue so that we can keep a track of it.

**Comment by EvHaus** [comment]
I was stuck getting it to work for a while too.

And then I figured out that you have to visit `http://yourapp?react_perf` instead of `http://yourapp`. Could that be the issue for you too @Anenth?
