### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by nuoyz** [nitin42/react-perf-devtool#19]
i uest react-create-app create a react project,

then add react-perf-devtool in index.js
like this: 
![image](https://user-images.githubusercontent.com/11713023/34935110-bacf02f0-fa17-11e7-942c-0713b5876d81.png)

but yarn build  get this error: 
![image](https://user-images.githubusercontent.com/11713023/34935047-80276796-fa17-11e7-9343-a652b99a49d1.png)
what i miss ?

**Comment by nitin42** [comment]
Ok! So `react-perf-devtool` is supposed to be a `devDependency` and not an actual dependency that you include in your production bundle. Plus, it will only work with development build of ReactDOM i.e `react-dom.developmen.min.js` and not the production build. So there is no need to include this in your bundle. Further, create-react-app does not transpile your dependencies. That's why you're getting this error.

The solution is, remove this hook from your index.js file or whatever file the hook is in and then build for the production. Hope it helps!

**Comment by jacobworrel** [comment]
My production build was failing in the minification step as well after adding react perf devtool, even if I excluded it from production like so:
`if (process.env.NODE_ENV !== 'production' && process.env.NODE_ENV !== 'test') {
  const registerObserver = require('react-perf-devtool');
  registerObserver();
}`

Seems to be because I was using v0.4.6 of Webpack's UglifyJS plugin under the webpack.optimize.UglifyJsPlugin alias, which doesn't support ES6. Does the 'react-app' Babel preset you're using transpile your code to ES5? Upgrading to the [latest version of the UglifyJS plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) solved the issue for me but I'm still kinda curious why this was happening in the first place... https://stackoverflow.com/questions/45870467/error-in-bundle-js-from-uglifyjs-name-expected

**Comment by nitin42** [comment]
I will look into this, hopefully today!

**Comment by nitin42** [comment]
Yeah! I was able to resolve this problem. Sorry @nuoyz and @jacobworrel for the late response!

I will release a minor update with a change log tomorrow. Stay tune!

Thanks 😃

**Comment by nitin42** [comment]
Updated and released a new version of the package, `3.0.4`. There are some minor changes in the syntax now.

**Earlier**

```js
const registerObserver = require('react-perf-devtool')

registerObserver()
```

**Current**

```js
const { registerObserver } = require('react-perf-devtool')

registerObserver()
```

**Comment by Azizbek0770** [comment]
![Screenshot 2024-03-02 043142](https://github.com/nitin42/react-perf-devtool/assets/161105396/f56e3409-f441-49c8-add0-db824f1fac37)

**Comment by Azizbek0770** [comment]
could you help please it`s not going to be fixed, I don`t know why, I tried several times
