### ISSUE TITLE
PerformanceObserver gets destroyed after some time

### ISSUE THREAD

**Issue by SDITrifork** [nitin42/react-perf-devtool#25]
This drove me crazy for some days. The PerformanceObserver as instantiated in registerObserver stops emitting measurements after a short time in some browsers.

### Observed in
- Firefox 58.0.2 (current)
- Chrome 59.0.3071.115, running in electron 1.8.2 (current).

### My theory
The PerformanceObserver instance as constructed in registerObserver in hook.js has no reference outside this scope and eventually gets destroyed by garbage collection.

### Temporary workaround
Return the observer from registerObserver and keep the reference somewhere safe. Works in all cases.

**Comment by nitin42** [comment]
Thanks!

Can you come up with a PR ? Not forcing you to make all the changes, but it will be easier (for both of us) to investigate the issue!

**Comment by nitin42** [comment]
Situation would have been different if we could use `PerformanceObserver` API inside the inspected window where the plugin lives. If I attempt to use `PerformanceObserver` API inside the plugin window, then it won't be able to listen to React measures. That's why we need to bridge both the things.

Also I was wondering if this issue isn't related to `PerformanceObserver` instance which gets destroyed after some time. It might be due to this query

```
this.clearMeasures()
```

This clears all the measures once we have updated the plugin state with updated measures.

Here is the code from the plugin.

```js
  updateMeasures = measures => {
    store = store.concat(measures)

    this.setState({
      perfData: store,
      totalTime: store
        .reduce((acc, comp) => acc + comp.totalTimeSpent, 0)
        .toFixed(2)
    })

    this.clearMeasures()
  }
```

**Comment by SDITrifork** [comment]
See #26 
I am actually not using the plug-in part of your work.
I am mostly interested in a nice an easy way to process the measures from react for analytics, hence why I only use hook.js.

**Comment by nitin42** [comment]
Do you find it useful ? I think it was only me who was using measures to send them to an Analytics service for visualisation.

**Comment by nitin42** [comment]
Thanks for the PR! I'll take a look at it later this evening!

**Comment by SDITrifork** [comment]
We aggregate the measures and keep averages for analysis. Also, we filter for peaks and persist them, too. 
It helps us an awful lot in quantifying performance after tests. Hook.js is IMO a really convenient way to handle the measures.

**Comment by nitin42** [comment]
Glad to hear that! That's awesome.

**Comment by nitin42** [comment]
Closing this issue in favour of #26 since that addresses the problem. I think returning the observer instance in `hook.js` and then managing it somewhere in your application codebase is very cumbersome. I think this is not a good practice! Anyway, open to feedback in case you want to reopen this issue.
