### ISSUE TITLE
react-dom comment

### ISSUE THREAD

**Issue by ZhaoWenbo6** [nitin42/react-perf-devtool#3]
"react-dom": "^16.1.1"
 comment this line: performance.clearMeasures(formattedLabel)

**Comment by nitin42** [comment]
Hi!

Well, with every new update of `react-dom` package, this may change. So it would be better if we could add a helpful suggestion to deal with this because I think it would be difficult to keep track of this line with every new release of `react-dom` package.

Also, React team will come up with an API for this so this will change (no longer rely on commenting this line).

Thanks!

**Comment by dandonahoe** [comment]
@nitin42 Thanks for explaining.

In the meantime, why not change the tutorial to show how to identify the correct line even if it changes a bit?

"Search for the line with `performance.clearMeasures` inside the `endMark` function"

**Comment by nitin42** [comment]
@dandonahoe some good stuff in the pipeline. The new version (V2) of the devtool will not require commenting the line in `react-dom` development bundle. V2 will use Performance Observer API and instead of querying the metrics (perf. measures), it will register a listener which will listen to the perf. measurement event. I am going to release V2 this week.

Merry Christmas!

**Comment by nitin42** [comment]
Plus, it will also support logging measures to the console. So you can inspect the stats in your console also (however you want).

**Comment by nitin42** [comment]
A new update has been released! Check out the docs before updating the devtool.
